
import Image from "next/image";
import Head from "next/head";

export default function Home() {



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          href="//netdna.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="static/" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
     <nav className="homeNav bg-info">
      <div className="logo h4 fw-bold">
        Interface d'administration
      </div>
      <div className="addUser btn btn-lg btn-outline-dark">+Add User</div>
     </nav>
     </main>
    </>
  );
}
